source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

workspace 'EasyPeasy'

# iOS

target 'Demo' do
  project 'EasyPeasy.xcodeproj'
  pod 'EasyPeasy', :path => '../'
end

target 'Tests' do
  project 'EasyPeasy.xcodeproj'
  pod 'EasyPeasy', :path => '../'
end

# macOS

target 'Demo macOS' do
  project 'Demo macOS/Demo macOS.xcodeproj'
  pod 'EasyPeasy', :path => '../'
end

target 'Tests macOS' do
  project 'Demo macOS/Demo macOS.xcodeproj'
  pod 'EasyPeasy', :path => '../'
end
