source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Demo', :exclusive => true do
  pod 'EasyPeasy', :path => '../'
end

target 'Tests', :exclusive => true do
  pod 'EasyPeasy', :path => '../'
end
