fastlane_version "1.66.0"
default_platform :ios

platform :ios do

  desc "Runs all the tests"
  lane :travis do
    project = "EasyPeasy.xcodeproj"

    # Run tests (iOS)
    scheme = "EasyPeasyTests"
    scan(
      scheme: scheme,
      project: project,
      device: "iPhone 6s",
      code_coverage: true
    )

    # Check code coverage (iOS)
    xcov(
      scheme: scheme,
      project: workspace,
      exclude_targets: "Demo-iOS.app,Demo-macOS.app",
      coveralls_service_name: "travis-ci",
      coveralls_service_job_id: ENV["TRAVIS_JOB_ID"]
    )
  end

end
