fastlane_version "1.66.0"
default_platform :ios

platform :ios do

  desc "Runs all the tests"
  lane :travis do
    scheme = "EasyPeasy"
    workspace = "Example/EasyPeasy.xcworkspace"

    # Run tests
    scan(
      scheme: scheme,
      workspace: workspace,
      destination: "platform=iOS Simulator,name=iPhone 6,OS=9.3",
      code_coverage: true
    )

    # Check code coverage
    xcov(
      scheme: scheme,
      workspace: workspace,
      exclude_targets: "Demo.app"
    )
  end

end
